routes/web.php
<?php

Route::get('/index', function () {
    return view('index');
});

Route::resource('product', 'Product\ProductController');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamps = false; //Desativando as timestamps do DB
    protected $fillable = ['name', 'description'];  //Determinando os campos que serão inseridos pelo usuário no DB
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Product/ProductController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->product->paginate(5);
        return view('products.selectProducts', compact('products'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.formProducts');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $dataForm = $request->except('_token');

        $insert = $this->product->insert($dataForm);

        if ($insert) {
            return redirect()->route('product.index');
        }

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {

    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->product->find($id);

        return view('products.editProduct', compact('product'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dataForm = $request->all();
        $product = $this->product->find($id);

        $update = $product->update($dataForm);

        if ($update) {
            return redirect()->route('product.index');
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->product->find($id);
        $delete = $product->delete();

        if ($delete) {
            return redirect()->route('product.index');
        }
    }

}

resources/views/index.blade.php
@extends('templates.home') 
@section('content')

<!-- CONTEUDO PRINCIPAL -->


<h2 class="text-center">CRUD de produtos</h2><br>
<img src="{{ URL::asset('images/productImage.png') }}" class="img-fluid rounded mx-auto d-block" alt=""><br>
<p>Este sistema realiza o CRUD de produtos utilizando o Laravel na versão 5.3</p>

<!-- CONTEUDO PRINCIPAL -->
@endsection

resources/views/products/editProduct.blade.php
@extends('templates.home') 
@section('content')

<!-- CONTEUDO PRINCIPAL -->
<h1 class="text-center">Editar produto: {{$product->name}}</h1>

<div class="container">
    <form class="form" action="{{route('product.update', $product->id)}}" method="POST">
        {!! method_field('PUT') !!}
        {!! csrf_field()!!}
        <div class="form-group">
            <label for="name">Novo nome do produto</label>
            <input type="text" class="form-control" name="name" id="nome" required="" placeholder="Digite o nome do produto" value="{{$product->name}}">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Nova descrição do produto</label>
            <textarea class="form-control" name="description" id="descricao" required="" rows="3" placeholder="Digite a descrição do produto">{{$product->description}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Editar</button>
    </form>
</div>

<!-- CONTEUDO PRINCIPAL -->
@endsection

resources/views/products/formProducts.blade.php
@extends('templates.home') 
@section('content')

<!-- CONTEUDO PRINCIPAL -->
<h1 class="text-center">Cadastrar novo produto</h1>

<div class="container">
    <form class="form" action="{{route('product.store')}}" method="POST">
        {!! csrf_field()!!}
        <div class="form-group">
            <label for="name">Nome do produto</label>
            <input type="text" class="form-control" name="name" id="nome" required="" placeholder="Digite o nome do produto">
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Descrição do produto</label>
            <textarea class="form-control" name="description" id="descricao" required="" rows="3" placeholder="Digite a descrição do produto"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
</div>

<!-- CONTEUDO PRINCIPAL -->
@endsection

resources/views/products/selectProducts.blade.php
@extends('templates.home') 
@section('content')

<!-- CONTEUDO PRINCIPAL -->
<h1 class="text-center">Produtos cadastrados</h1>
<div class="container">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Descricao</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
            <tr>
                <td>{{$product->id}}</td>
                <td>{{$product->name}}</td>
                <td>{{$product->description}}</td>
                <td> <a href="{{route('product.edit', $product->id)}}"> <button type="button" class="btn btn-warning">Editar</button> </a></td>
                <td>
                <form action="product/{{ $product->id }}" method="POST">
                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="submit" name="name" value="Deletar" class="btn btn-danger">
                </form>
            </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {!! $products->links() !!}
        </ul>
    </nav>




</div>
<!-- CONTEUDO PRINCIPAL -->
@endsection

resources/views/templates/home.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{{ URL::asset('css/style.css') }}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
        crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous">

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous">

    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous">

    </script>

    <title>Página principal</title>
</head>

<body>

    <!-- INICIO HEADER -->
    <header>
        <div class="container">
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand" href="#">
                <img src="{{ URL::asset('images/logoIcon.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
                Sistema gerenciador de produtos
            </a>
            </nav>
        </div>
    </header>
    <!-- FIM HEADER -->

    <div class="container">
        <div class="sidebar">
            <a class="active" href="../index">Página principal</a>
            <a href="{{route('product.create')}}">Inserir novo produto</a>
            <a href="{{route('product.index')}}">Consultar produtos registrados</a>
        </div>
        <div class="content">
            @yield('content')
        </div>

    </div>
    <!-- INICIO FOOTER -->
    <div class="fixed-bottom">
        <div class="footer">
            <div class="container">
                <p class="text-muted text-center">®Desenvolvido por Lucas Vinicius</p>
            </div>
        </div>
    </div>
    <!-- FIM FOOTER -->

</body>

</html>